apiVersion: gateway.solo.io/v1
kind: ListenerOption
metadata:
  name: access-logs
  namespace: ingress-gw
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gw
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          path: /dev/stdout
          jsonFormat:
            timestamp: "%START_TIME%"
            server_name: "%REQ(:AUTHORITY)%"
            response_duration: "%DURATION%"
            request_command: "%REQ(X-ENVOY-ORIGINAL-METHOD?:METHOD)%"
            request_uri: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            request_protocol: "%PROTOCOL%"
            status_code: "%RESPONSE_CODE%"
            client_address: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
            x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
            bytes_sent: "%BYTES_SENT%"
            bytes_received: "%BYTES_RECEIVED%"
            user_agent: "%REQ(USER-AGENT)%"
            downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
            requested_server_name: "%REQUESTED_SERVER_NAME%"
            request_id: "%REQ(X-REQUEST-ID)%"
            response_flags: "%RESPONSE_FLAGS%"
            route_name: "%ROUTE_NAME%"
            upstream_cluster: "%UPSTREAM_CLUSTER%"
            upstream_host: "%UPSTREAM_HOST%"
            upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
            upstream_service_time: "%REQ(x-envoy-upstream-service-time)%"
            upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
            correlation_id: "%REQ(X-CORRELATION-ID)%"
            user_id: "%DYNAMIC_METADATA(envoy.filters.http.ext_authz:userId)%"
            api_product_id: "%DYNAMIC_METADATA(io.solo.gloo.portal:api_product_id)%"
            api_product_name: "%DYNAMIC_METADATA(io.solo.gloo.portal:api_product_name)%"
            api_version: "%DYNAMIC_METADATA(io.solo.gloo.portal:api_version)%"
            custom_metadata-api_category: "%DYNAMIC_METADATA(io.solo.gloo.portal.custom_metadata:api-category)%"
            custom_metadata-pii_sensitive: "%DYNAMIC_METADATA(io.solo.gloo.portal.custom_metadata:pii-sensitive)%"